### ISSUE TITLE
0.5.8: In a Firefox Windows to Chrome Mac connection, incomingStream video is black

### ISSUE THREAD

**Issue by letchoo** [Temasys/SkylinkJS#91] opened 2015-02-28 05:47 UTC
It seems like with a Firefox (windows) to Chrome (mac) connection, when incomingStream is invoked, the receiving video stream both ends is an empty blob video.

This happens mostly with the Firefox versions running on the windows platform.

**Comment by tienthanh8490** [comment] 2015-11-12 06:07
Not reproducible since Firefox 40+ . Closing.

**Closed by tienthanh8490** 2015-11-12 06:07 UTC
Labels: bug
