### ISSUE TITLE
Skylink MCU [0.6.12]

### ISSUE THREAD

**Issue by amangupta26** [Temasys/SkylinkJS#228] opened 2016-05-18 10:08 UTC
While using MCU App Key after users have joined the room and started videos. If one user mutes the audio, the video it is receiving stucks and remain at same frame. But if the user unmutes the audio, the video starts running fine. 
  I guess this is because video and audio are demultiplexed as separate streams for MCU and relay server only serves video. For the audio side, all audio channels are multiplexed and broadcasted to all users and is completely independent of video.
  Is this behavior expected, the way Skylink is implementing the MCU/relays or is this a bug?

P.S. : Could anyone point out a good documentation about how MCU works in Skylink(like what is priveleged user, what is peer introduction, architecture etc) so that we could have better understanding about it.

**Comment by letchoo** [comment] 2016-05-20 04:04
Hi @amangupta26,

We were unable to reproduce in our own demo [getaroom.io](https://getaroom.io).

Which are the environments you were testing on?

As for the MCU documentation, it should technically work like P2P except that the [`serverPeerJoined`](https://cdn.temasys.com.sg/skylink/skylinkjs/0.6.x/doc/classes/Skylink.html#event_serverPeerJoined), [`serverPeerRestart`](https://cdn.temasys.com.sg/skylink/skylinkjs/0.6.x/doc/classes/Skylink.html#event_serverPeerRestart) and [`serverPeerLeft`](https://cdn.temasys.com.sg/skylink/skylinkjs/0.6.x/doc/classes/Skylink.html#event_serverPeerLeft) events, and a differing workflow (temporarily) in [here](http://support.temasys.com.sg/support/discussions/topics/12000002853). 

The MCU works basically like it's a server room based technology, where instead of sending media p2p for multiway, it allows you to have to upload once and media is transferred from the MCU/SFU to everyone else.

<img width="716" alt="mcu streaming diagram" src="https://cloud.githubusercontent.com/assets/4675614/15416885/9a0fa19a-1e82-11e6-80f8-6af61c0bb1ff.png">

As for the documentation, we are still currently working on it.

**Comment by letchoo** [comment] 2016-05-24 12:29
Hi @amangupta26, did you managed to test with our own demo [getaroom.io](https://getaroom.io) and check if it's reproducible?

**Comment by amangupta26** [comment] 2016-05-24 12:34
Hi @letchoo , got busy in another project. Could you give me more time before I test it again.

**Comment by letchoo** [comment] 2016-05-24 12:38
Hi @amangupta26, no worries and no rush to that. Just checking in if there's anything we can help.

**Comment by jeromeking** [comment] 2016-07-16 21:32
My app key works fine and I changed the demo key to be mine but when I refresh the page it says "404 Not Found".

Test on my site vidlinks.net

**Comment by letchoo** [comment] 2016-07-17 18:35
Hey @jeromeking, this seems to be an issue from your web application, I suggest that perhaps you check if the html page exists or the web server configuration.

Or if this happens to be an API response, please copy and paste it here so we may evaluate the issues to rectify it.

**Comment by geekavi** [comment] 2018-02-21 08:52
close issue as no response.

**Closed by geekavi** 2018-02-21 08:52 UTC
Labels: question
