### ISSUE TITLE
Missing close button in unsupported browser - safari mobile 10

### ISSUE THREAD

**Issue by erichstark** [Temasys/SkylinkJS#279] opened 2017-01-25 09:25 UTC
Hello SkylinkJS team,
I found a bug on safari mobile, when library is not supported it is not possible to close this warning. And therefore webpage is not usable beacause on top of page we have "hamburget button" for menu. Is there any workaround?

![img_1302](https://cloud.githubusercontent.com/assets/1123805/22284578/358cd55a-e2e8-11e6-811c-a4b584e25ec4.PNG)

**Comment by oooookk7** [comment] 2017-01-25 10:11
Hey @erichstark,

This is a styling issue caused by the `AdapterJS.renderNotificationBar()` function from the AdapterJS dependency that SkylinkJS uses.

To resolve this issue, you might need to modify the [adapter.screenshare.js file](https://github.com/Temasys/AdapterJS/blob/master/publish/adapter.screenshare.js#L395) and tweak the CSS to suit your webpage and use your own customized modified AdapterJS dependency.

You might need to reference the dependencies separately though if you are using `skylink.complete.js` as it would be pointing to the different versions of the dependencies since it is a compiled version of SkylinkJS+AdapterJS+socket.io-client:

```
<-- recommended order -->
<script src="https://cdn.socket.io/socket.io-1.4.8.js"></script>
<script src="my-adapter.screenshare.js"></script>
<script src="https://cdn.temasys.com.sg/skylink/skylinkjs/0.6.x/skylink.debug.js"></script>
```

**Comment by oooookk7** [comment] 2017-01-25 10:12
I'll be closing this ticket on this github project as well since this issue stems from AdapterJS, and if there is any issues, please open a ticket on the AdapterJS project [here](https://github.com/Temasys/AdapterJS/issues).

**Closed as completed by oooookk7** 2017-01-25 10:12 UTC
