### ISSUE TITLE
Cant show both video stream and screen share at the same page

### ISSUE THREAD

**Issue by danishnazir** [Temasys/SkylinkJS#273] opened 2016-12-02 12:13 UTC
Hello i am trying to integrate both screen share and video sharing at the same page,The upload of them was successful but at the receiving end only screen share is visible it overwrites the video element but i am using different video elements one for screen share and one for video streaming

**Comment by oooookk7** [comment] 2016-12-03 05:38
Hi @danishnazir, currently our SDK only supports single stream sending. Multi-stream support is planned but for the future releases.

**Comment by danishnazir** [comment] 2016-12-03 06:24
Hi @letchoo but the thing is the screen share and the video streaming are both played using html5 video tag so how can i differentiate between the two whether that there it is a video stream or its a screen share plus i was able to achieve both stream and screenshare at the same page but the thing is i cant differentiate between the two is there a method to differentiate them ?

**Comment by oooookk7** [comment] 2016-12-03 06:33
Hi @danishnazir, 

If you are using events like [`mediaAccessSuccess`](https://cdn.temasys.com.sg/skylink/skylinkjs/0.6.x/doc/classes/Skylink.html#event_mediaAccessSuccess) or [`incomingStream`](https://cdn.temasys.com.sg/skylink/skylinkjs/0.6.x/doc/classes/Skylink.html#event_incomingStream), there is a parameter payload called the `isScreensharing` to distinguish if the Stream received is screensharing stream or not.

Additionally, in the `peerInfo` payload parameter, there should be a flag called [`peerInfo.video.screenshare`](https://cdn.temasys.com.sg/skylink/skylinkjs/0.6.x/doc/classes/Skylink.html#event_peerJoined) when video is enabled in the Stream to distinguish between screensharing Stream or not.

**Comment by danishnazir** [comment] 2016-12-03 06:38
Hi @letchoo thanks for your fast reply.
I will look into it and try to implement that i am using different events like mediaaccesssuccess and other events like incomingstream and peerjoined. Thanks once again for your fast reply i highly appreciate that.

**Comment by oooookk7** [comment] 2016-12-03 06:39
Alright, welcome. If there are no more enquiries, I'll close this ticket since the original question on displaying 2 streams is answered.

Btw as a tip, [`shareScreen()`](https://cdn.temasys.com.sg/skylink/skylinkjs/0.6.x/doc/classes/Skylink.html#method_shareScreen), [`sendStream()`](https://cdn.temasys.com.sg/skylink/skylinkjs/0.6.x/doc/classes/Skylink.html#method_sendStream) and [`getUserMedia()`](https://cdn.temasys.com.sg/skylink/skylinkjs/0.6.x/doc/classes/Skylink.html#method_getUserMedia) has `callback` parameter which is triggered with errors (`callback(error,..)`) or the stream (`callback(..., success)`)  itself. Note that the difference between `getUserMedia()` and `sendStream()` is that `getUserMedia()` is meant to be called before User is in the Room (caused by `joinRoom()`) and `sendStream()` is after User is in the Room.

**Closed as completed by oooookk7** 2016-12-03 06:39 UTC

**Comment by Pawan-Bishnoi** [comment] 2018-03-16 14:36
Hi,
Stirring up an closed issue but: 

I have similar requirement (need to run video with screenshare).
Can I use two instances of Skylink to achieve this?
And call joinRoom on both and publishStream from both?

I tried it but it looks like whenever one joinRoom succeeds, the other one gets kicked out.

Is this even possible?

Thanks !

**Comment by alsmyr** [comment] 2018-03-16 20:25
We are using Skylink and have the same requirement. We use two connections as you suggest above and it works fine.
