### ISSUE TITLE
Cannot read property 'sid' of null

### ISSUE THREAD

**Issue by MichaelJCole** [Temasys/SkylinkJS#147] opened 2015-11-02 17:28 UTC
Hey there, I'm getting an error trying to turn off screen sharing.

```
Uncaught TypeError: Cannot read property 'sid' of null
streamEnded @ skylink.complete.js:20453
```

I'm using this in a Meteor application:

```
Template.conference.events({
  'click #toggleChat': function(e, template) {     // <----------  These are event handlers.
    template.showChat.set(!template.showChat.get());
  },
  'click #toggleShare': function(e, template) {
    if (template.shareScreen.get()) {   // <--------  This is a reactive variable.
console.log('turning off ...');
      template.skylink.stopScreen(function(err) {   // <----  This isn't throwing an error or calling the callback
        if (err) throw err;     
console.log('... off');
        template.shareScreen.set(false);
      });
    } else {
console.log('turning on ...');
      template.skylink.shareScreen(function(err) {
        if (err) throw err;
console.log('... on');
        template.shareScreen.set(true);
      });
    }
  },
```

Here's the full console output:
```
turning on ...   
... on
turning off ...
Uncaught TypeError: Cannot read property 'sid' of null
streamEnded @ skylink.complete.js:20453
```

```
  <script src="//cdn.temasys.com.sg/skylink/skylinkjs/0.6.x/skylink.complete.js"></script>
```

Any suggestions?  

Thanks!

**Comment by letchoo** [comment] 2015-11-03 02:36
Hi @MichaelJCole,

Thanks for raising the issue. Was this done with the Skylink Media Relay on?

**Comment by MichaelJCole** [comment] 2015-11-03 13:31
Hey @letchoo I think that's on by default.  Anyways, I didn't fiddle with it.   Here's the code that starts the session:

```
  var self = this;
  var confId = Template.instance().data.conference.id;
  self.skylink.init({
    appKey: Meteor.settings.public.skylink,
    apiKey: Meteor.settings.public.skylink,
  }, function(err) {
    if (err) console.log(err);
    // Join the room.
    self.skylink.joinRoom(
      confId,
      { audio: true },  // Video is not set here for people w/o cameras.  Audio is required or connect will fail.
      function(err) { if (err) console.log(err); }
    );
  });
```

**Comment by letchoo** [comment] 2015-11-13 11:11
Hi @MichaelJCole,

Is this reproducible now for you? We are trying to reproduce this error.
May we know the events used and the subsequent application logic?

**Comment by ncurrier** [comment] 2015-11-13 11:14
@letchoo IIRC this was identified to be a problem on the Meteor side that was resolved, looks like we missed closing this ticket @MichaelJCole can you please confirm this so we can close this out.

**Comment by MichaelJCole** [comment] 2015-11-13 18:39
Yes, I think this was because I was passing `null` as a room id to `joinRoom()`.

Adding parameter checks to `joinRoom()` might save you some support issues in the future.  I can be a crappy programmer at times, but definitely not the worst :-)

Thanks for following up :-)

**Comment by letchoo** [comment] 2015-11-19 13:36
Added checks for `skylink.joinRoom(null);`. This should throw an error in the callback.

https://github.com/Temasys/SkylinkJS/releases/tag/0.6.4

**Comment by letchoo** [comment] 2015-12-23 23:19
Hi @MichaelJCole, I would like to check if the 0.6.4 release did fix the issue you have. Does it still occur for you?

**Comment by MichaelJCole** [comment] 2015-12-24 15:06
Hey Leticia, thanks for checking in.  I switched to SimpleWebRTC with a Xirsys backend.

**Comment by letchoo** [comment] 2015-12-29 04:19
Thanks for the response, we will be closing this ticket then.

**Closed** 2015-12-29 04:19 UTC
Labels: bug
