### ISSUE TITLE
incomingStream is not fired all the time

### ISSUE THREAD

**Issue by DefrenneD** [Temasys/SkylinkJS#72] opened 2015-01-16 12:33 UTC
I have a problem with Skylink and I can't figure out why.

Sometimes, the event incomingStream is fired, and the next time it is not.

I'm running this code on http://localhost:3000.

    <html>
    <head lang="en">
        <meta charset="UTF-8">
        <title></title>
        <script src="//cdn.temasys.com.sg/skylink/skylinkjs/0.5.x/skylink.complete.min.js"></script>

        <script>
            // Getting started on how to use Skylink
        var skylink = new Skylink();

        skylink.on('peerJoined', function (peerId, peerInfo, isSelf) {
            console.log('peerJoined');
        });

        skylink.on('incomingStream', function (peerId, stream, isSelf) {
            console.log('incomingStream');

        });

        skylink.on('mediaAccessSuccess', function (stream) {
            console.log('mediaAccessSuccess');
        });

        skylink.init({
            apiKey: 'MY API KEY FOR LOCALHOST',
            defaultRoom: generateUUID()
        });

        skylink.joinRoom({
            audio: true,
            video: true
        });

        function generateUUID() {
            var d = new Date().getTime();
            var uuid = 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, function (c) {
                var r = (d + Math.random() * 16) % 16 | 0;
                d = Math.floor(d / 16);
                return (c == 'x' ? r : (r & 0x7 | 0x8)).toString(16);
            });
            return uuid;
        };

    </script>
    </head>
    <body>
    </body>
    </html>

The output is either

     mediaAccessSuccess

or

    mediaAccessSuccess
    incomingStream
    peerJoined

**Comment by serrynaimo** [comment] 2015-01-16 12:45
Hey, 

try this:

skylink.init({ apiKey: '' }, function() {
     skylink.joinRoom({ audio: true, video: true });
});

hope this helps

**Comment by DefrenneD** [comment] 2015-01-16 15:30
Thank you for your answer, I've tried it but it didn't work out... I still have the same problem.

Sometimes I got the "incomingStream" event, sometimes no.

Does Skylink have some kind of api call "limits" ?

**Comment by serrynaimo** [comment] 2015-01-16 15:33
There is currently a bug that only allows signaling messages to be send every 1 second. Gonna be resolved in 0.5.8 soon.

**Comment by serrynaimo** [comment] 2015-01-17 09:22
DefrenneD, in order to investigate that better, would you mind sharing where you are located and which of our signaling location you're using? US or APAC? (Default is US)

Thanks!

**Comment by DefrenneD** [comment] 2015-01-17 13:56
I didn't change the default so I'm using US and I'm located in Spain, Malaga.

Thanks

**Comment by serrynaimo** [comment] 2015-01-19 03:14
We can't reproduce the issue here at the office in chrome/ff/opera/safari. Can you give us a bit more info about your environment?

**Comment by DefrenneD** [comment] 2015-01-19 07:10
I'm using Chrome Version 39.0.2171.99 m, on Windows 8.
I have the same issue with Firefox 34.0.
I've tried with both US server and APAC server.

I'm located in Spain, Malaga.

Thanks for your help!

**Comment by serrynaimo** [comment] 2015-02-11 09:27
@DefrenneD so we have a new release in the making, maybe it'll solve your problem. Try it from here
//cdn.temasys.com.sg/skylink/skylinkjs/dev/0.5.9/skylink.complete.min.js and let us know!

**Comment by serrynaimo** [comment] 2015-03-04 09:12
We've now released the official 0.5.9 version. Hope that fixes your problem.
//cdn.temasys.com.sg/skylink/skylinkjs/0.5.9/skylink.complete.min.js

Cheers!

**Closed by serrynaimo** 2015-03-04 09:12 UTC
